version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    networks:
      - compose-network
    environment:
      - REACT_APP_BACKEND_URL=http://backend:5050

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5050:5050"
    depends_on:
      - mongodb
    networks:
      - compose-network
    environment:
      - MONGO_URI=mongodb://mongodb:27017/mydatabase

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
       - mongodb_data:/data/db
    networks:
      - compose-network

networks:
  compose-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local