steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'frontend-image', './mern/frontend']
    id: 'build frontend docker image'
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['tag', 'frontend-image', 'us-central1-docker.pkg.dev/app-development-446013/mern-k8s/frontend-image']
    id: 'tag frontend image'
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/app-development-446013/mern-k8s/frontend-image']
    id: 'push frontend image'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'backend-image', './mern/backend']
    id: 'build bakcend docker image'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['tag', 'backend-image', 'us-central1-docker.pkg.dev/app-development-446013/mern-k8s/backend-image']
    id: 'tag backend image'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/app-development-446013/mern-k8s/backend-image']
    id: 'push backend image'

options:
  logging: CLOUD_LOGGING_ONLY